module Dkit
  module ShellHook
    module_function

    def generate
      <<~'ZSH'
        # Generated by: dkit hook
        # Add to ~/.zshrc: eval "$(dkit hook)"

        _DKIT_ROOT=""
        _DKIT_ACTIVE_CMDS=()
        _DKIT_GLOB_PATTERNS=()
        _DKIT_GLOB_CMDS=()

        _dkit_reset() {
          local cmd
          for cmd in "${_DKIT_ACTIVE_CMDS[@]}"; do
            unfunction "$cmd" 2>/dev/null
          done
          _DKIT_ACTIVE_CMDS=()
          _DKIT_GLOB_PATTERNS=()
          _DKIT_GLOB_CMDS=()
        }

        _dkit_verbose_fallback() {
          [[ "${DKIT_VERBOSE}" == "0" || -z "${_DKIT_ROOT}" ]] && return
          local _ic="${_DKIT_ROOT}/.devcontainer/dkit-intercept"
          grep -qxF 'verbose: false' "$_ic" 2>/dev/null && return
          printf '\033[31m[dkit] %s → host (fallback)\033[0m\n' "$1" >&2
        }

        _dkit_expand_glob() {
          local root="$1" pattern="$2"
          local full_pattern="$root/$pattern"
          local matches=( ${~full_pattern}(N*) )
          local m rel
          for m in "${matches[@]}"; do
            rel="${m#$root/}"
            (( ${_DKIT_ACTIVE_CMDS[(Ie)$rel]} )) && continue
            eval "function ${rel}() {
              if dkit status --quiet 2>/dev/null; then
                dkit run ${rel} \"\$@\"
              else
                _dkit_verbose_fallback \"${rel}\"
                command ${rel} \"\$@\"
              fi
            }"
            _DKIT_ACTIVE_CMDS+=("${rel}")
            _DKIT_GLOB_CMDS+=("${rel}")
          done
        }

        _dkit_refresh_globs() {
          [[ -z "$_DKIT_ROOT" || ${#_DKIT_GLOB_PATTERNS[@]} -eq 0 ]] && return
          local cmd
          for cmd in "${_DKIT_GLOB_CMDS[@]}"; do
            if [[ ! -e "$_DKIT_ROOT/$cmd" ]]; then
              unfunction "$cmd" 2>/dev/null
              _DKIT_ACTIVE_CMDS=("${(@)_DKIT_ACTIVE_CMDS:#$cmd}")
            fi
          done
          _DKIT_GLOB_CMDS=()
          local pat
          for pat in "${_DKIT_GLOB_PATTERNS[@]}"; do
            _dkit_expand_glob "$_DKIT_ROOT" "$pat"
          done
        }

        _dkit_load() {
          local root="$1"
          local intercept="$root/.devcontainer/dkit-intercept"
          [[ -f "$intercept" ]] || return
          local cmd
          while IFS= read -r cmd; do
            [[ -z "$cmd" || "${cmd[1]}" == "#" ]] && continue
            # Trim whitespace
            cmd="${cmd## }"
            cmd="${cmd%% }"
            [[ -z "$cmd" ]] && continue
            # Glob pattern: expand matching executables
            if [[ "$cmd" == *[\*\?\[]* ]]; then
              _DKIT_GLOB_PATTERNS+=("${cmd}")
              _dkit_expand_glob "$root" "$cmd"
              continue
            fi
            eval "function ${cmd}() {
              if dkit status --quiet 2>/dev/null; then
                dkit run ${cmd} \"\$@\"
              else
                _dkit_verbose_fallback \"${cmd}\"
                command ${cmd} \"\$@\"
              fi
            }"
            _DKIT_ACTIVE_CMDS+=("${cmd}")
          done < "$intercept"
        }

        _dkit_chpwd() {
          # Fast path: still inside the same project root
          if [[ -n "$_DKIT_ROOT" && "$PWD" == "$_DKIT_ROOT"* ]]; then
            return
          fi
          local new_root
          new_root="$(dkit root 2>/dev/null || echo '')"
          [[ "$new_root" == "$_DKIT_ROOT" ]] && return
          _dkit_reset
          _DKIT_ROOT="$new_root"
          [[ -n "$new_root" ]] && _dkit_load "$new_root"
        }

        # Special commands — always available, always route to devcontainer
        code() {
          if dkit status --quiet 2>/dev/null; then
            dkit code "$@"
          else
            _dkit_verbose_fallback "code"
            command code "$@"
          fi
        }

        claude() {
          if dkit status --quiet 2>/dev/null; then
            dkit claude "$@"
          else
            _dkit_verbose_fallback "claude"
            command claude "$@"
          fi
        }

        autoload -U add-zsh-hook
        add-zsh-hook chpwd _dkit_chpwd
        add-zsh-hook precmd _dkit_refresh_globs
        _dkit_chpwd
      ZSH
    end
  end
end
